services:
  mysql:
    image: mysql:8.0
    container_name: springboot-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
